// <auto-generated />
using Lab17Cameron.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab17Cameron.Migrations
{
    [DbContext(typeof(Lab17CameronContext))]
    [Migration("20171004183557_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab17Cameron.Models.Destination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SeasonID");

                    b.Property<string>("State");

                    b.HasKey("DestinationID");

                    b.ToTable("Destination");
                });

            modelBuilder.Entity("Lab17Cameron.Models.Season", b =>
                {
                    b.Property<int>("SeasonID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DestinationID");

                    b.Property<int>("Fall");

                    b.Property<int>("Spring");

                    b.Property<int>("Summer");

                    b.Property<int>("Winter");

                    b.HasKey("SeasonID");

                    b.ToTable("Season");
                });

            modelBuilder.Entity("Lab17Cameron.Models.Supplies", b =>
                {
                    b.Property<int>("SuppliesID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Qty");

                    b.Property<bool>("Required");

                    b.Property<int>("SeasonID");

                    b.HasKey("SuppliesID");

                    b.ToTable("Supplies");
                });
#pragma warning restore 612, 618
        }
    }
}
