// <auto-generated />
using Lab17Tom.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab17Tom.Migrations
{
    [DbContext(typeof(Lab17TomContext))]
    partial class Lab17TomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab17Tom.Models.Destinations", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Name");

                    b.Property<int>("WeatherID");

                    b.HasKey("DestinationID");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("Lab17Tom.Models.Supplies", b =>
                {
                    b.Property<int>("SupplyID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DestinationID");

                    b.Property<bool>("IsRequired");

                    b.Property<string>("Name");

                    b.Property<int>("Qty");

                    b.Property<decimal>("Volume");

                    b.Property<int>("WeatherID");

                    b.Property<decimal>("Weight");

                    b.HasKey("SupplyID");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("Lab17Tom.Models.Weather", b =>
                {
                    b.Property<int>("WeatherID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Climate");

                    b.HasKey("WeatherID");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
