// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TravelPackersLab17.Models;

namespace TravelPackersLab17.Migrations
{
    [DbContext(typeof(TravelPackersLab17Context))]
    [Migration("20171004184225_newControllers")]
    partial class newControllers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelPackersLab17.Models.Destination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Country");

                    b.Property<string>("Location");

                    b.Property<int>("WeatherID");

                    b.HasKey("DestinationID");

                    b.ToTable("Destination");
                });

            modelBuilder.Entity("TravelPackersLab17.Models.Supplies", b =>
                {
                    b.Property<int>("SupplyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.Property<decimal>("Volume");

                    b.Property<int>("WeatherID");

                    b.Property<decimal>("Weight");

                    b.HasKey("SupplyID");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("TravelPackersLab17.Models.Weather", b =>
                {
                    b.Property<int>("WeatherID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Climate");

                    b.Property<int>("SuppliesID");

                    b.HasKey("WeatherID");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
