// <auto-generated />
using lab17miya.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace lab17miya.Migrations
{
    [DbContext(typeof(lab17miyaContext))]
    partial class lab17miyaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("lab17miya.Models.Destination", b =>
                {
                    b.Property<int>("DestinationID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<int>("WeatherID");

                    b.HasKey("DestinationID");

                    b.ToTable("Destination");
                });

            modelBuilder.Entity("lab17miya.Models.Supplies", b =>
                {
                    b.Property<int>("SupplyID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("Quantity");

                    b.Property<int>("WeatherID");

                    b.HasKey("SupplyID");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("lab17miya.Models.Weather", b =>
                {
                    b.Property<int>("WeatherID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("WeatherType");

                    b.HasKey("WeatherID");

                    b.ToTable("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
